export { default as Hero } from "./Hero.astro"
export { default as About } from "./About.astro"
export { default as Skills } from "./Skills.astro"
export { default as Contact } from "./Contact.astro"
export { default as Footer } from "./Footer.astro"
