import {
    HtmlIcon,
    CssIcon,
    JsIcon,
    TsIcon,
    ReactIcon,
    NextIcon,
    AstroIcon,
    TailwindIcon,
    ReactQueryIcon,
    ReduxIcon,
    ZustandIcon,
    D3JsIcon,
    NanostoresIcon,
    NodeIcon,
    ExpressIcon,
    MongoIcon,
    FirebaseIcon,
    EdgeStoreIcon,
    MysqlIcon,
    PhpIcon,
    RestApiIcon,
    GdriveIcon,
    NextAuthIcon,
    PythonIcon,
    CppIcon,
    JavaIcon,
    ViteIcon,
    SocketIoIcon,
    NpmIcon,
    GitIcon,
    NetlifyIcon,
    VercelIcon,
    VsCodeIcon,
    FigmaIcon,
    PreactIcon,
    GSAPIcon,
    FramerMotionIcon,
    BunIcon,
    RIcon
} from "../assets/Icons";
import { GithubIcon } from "../assets/SVGs";

export const FrontendStack = [
    {
        name: "HTML",
        icon: HtmlIcon,
        link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    },
    {
        name: "CSS",
        icon: CssIcon,
        link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    },
    {
        name: "JavaScript",
        icon: JsIcon,
        link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    },
    {
        name: "TypeScript",
        icon: TsIcon,
        link: "https://www.typescriptlang.org/",
    },
    { name: "React.js", icon: ReactIcon, link: "https://react.dev/" },
    { name: "Next.js", icon: NextIcon, link: "https://nextjs.org/" },
    { name: "Astro", icon: AstroIcon, link: "https://astro.build/" },
    { name: "Tailwind", icon: TailwindIcon, link: "https://tailwindcss.com/" },
    {
        name: "TS Query",
        icon: ReactQueryIcon,
        link: "https://tanstack.com/query/latest/",
    },
    { name: "GSAP", icon: GSAPIcon, link: "https://gsap.com/" },
    { name: "Motion", icon: FramerMotionIcon, link: "https://www.framer.com/motion/" },
    { name: "Redux", icon: ReduxIcon, link: "https://redux.js.org/" },
    {
        name: "Zustand",
        icon: ZustandIcon,
        link: "https://zustand-demo.pmnd.rs/",
    },
    { name: "D3.js", icon: D3JsIcon, link: "https://d3js.org/" },
    { name: "Preact.js", icon: PreactIcon, link: "https://preactjs.com/" },
    {
        name: "Nanostores",
        icon: NanostoresIcon,
        link: "https://github.com/nanostores/nanostores",
    },
];
export const BackendStack = [
    { name: "Node.js", icon: NodeIcon, link: "https://nodejs.org/" },
    { name: "Express.js", icon: ExpressIcon, link: "https://expressjs.com/" },
    { name: "MongoDB", icon: MongoIcon, link: "https://www.mongodb.com/" },
    {
        name: "Firebase",
        icon: FirebaseIcon,
        link: "https://firebase.google.com/",
    },
    { name: "Edge Store", icon: EdgeStoreIcon, link: "https://edgestore.dev/" },
    { name: "MySQL", icon: MysqlIcon, link: "https://www.mysql.com/" },
    { name: "PHP", icon: PhpIcon, link: "https://www.php.net/" },
    {
        name: "REST API",
        icon: RestApiIcon,
        link: "https://developer.mozilla.org/en-US/docs/Glossary/REST",
    },
    {
        name: "Drive API",
        icon: GdriveIcon,
        link: "https://developers.google.com/drive",
    },
    {
        name: "Auth.js",
        icon: NextAuthIcon,
        link: "https://authjs.dev/",
    },
];

export const ProgrammingStack = [
    {
        name: "JavaScript",
        icon: JsIcon,
        link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    },
    {
        name: "TypeScript",
        icon: TsIcon,
        link: "https://www.typescriptlang.org/",
    },
    { name: "Python", icon: PythonIcon, link: "https://www.python.org/" },
    { name: "C++", icon: CppIcon, link: "https://isocpp.org/" },
    { name: "Java", icon: JavaIcon, link: "https://www.oracle.com/java/" },
    { name: "R", icon: RIcon, link: "https://www.r-project.org/" },
];

export const ToolsStack = [
    { name: "NPM", icon: NpmIcon, link: "https://www.npmjs.com/" },
    { name: "Bun", icon: BunIcon, link: "https://bun.sh/" },
    { name: "Git", icon: GitIcon, link: "https://git-scm.com/" },
    { name: "GitHub", icon: GithubIcon, link: "https://github.com/" },
    { name: "Vite.js", icon: ViteIcon, link: "https://vitejs.dev/" },
    { name: "Socket.io", icon: SocketIoIcon, link: "https://socket.io/" },
    { name: "Netlify", icon: NetlifyIcon, link: "https://www.netlify.com/" },
    { name: "Vercel", icon: VercelIcon, link: "https://vercel.com/" },
    {
        name: "VS Code",
        icon: VsCodeIcon,
        link: "https://code.visualstudio.com/",
    },
    { name: "Figma", icon: FigmaIcon, link: "https://www.figma.com/" },
];