export { default as Header } from "./Header.astro"
export { default as MobileHeader } from "./MobileHeader.astro"
export { default as SectionTitle } from "./SectionTitle.astro"
export { default as CenterTitle } from "./CenterTitle.astro"
export { default as SkillTitle } from "./SkillTitle.astro"
